print ("hello world")
print ("i am 11")
print ("i am in 6th grade")
print ("i love goa")
print ("my name is barbare")
print ("i love my friends")
print ("i love kutaisi")
print ("i like programming")
print ("my friend is 12")
print ("i love going out")
print ("goa is the best")
print ("i wake up at 10am")
print ("i love georgian dance")
print ("this is my homework")
print ("i am good at sports")
print ("pets are cute")
print ("i went to school yesterday")
print ("my school is nice")
print ("dancing is my hobby")
print ("my favorite pets are dogs ")
